"""End-to-end pipeline integration tests.

NOTE: These tests require:
- Blender installed (for Studio stage)
- FFmpeg installed (for Encoder stage)
- ChromaDB with test song data

They are slow (~minutes per test) and should be run separately from unit tests.

Run with: pytest tests/integration/ -v -s
"""

import pytest
from pathlib import Path


@pytest.mark.integration
@pytest.mark.slow
def test_director_to_studio_integration(tmp_path):
    """Test Director → Studio pipeline integration.

    Verifies that timeline.json generated by Director can be consumed by Studio.
    """
    from director.timeline import generate_timeline
    from studio.renderer import render_video

    # This test requires a real song in ChromaDB
    pytest.skip("Requires test data in ChromaDB - run manually")

    # Generate timeline
    timeline_path = tmp_path / "timeline.json"
    timeline = generate_timeline(
        audio_path="./test_audio.wav",
        song_id="test_song",
        theme_name="sponsor_neon",
        output_path=str(timeline_path)
    )

    assert timeline_path.exists()
    assert "events" in timeline
    assert len(timeline["events"]) > 0

    # Render with Studio (placeholder mode)
    video_path = tmp_path / "video.mp4"
    result = render_video(
        timeline_path=str(timeline_path),
        output_path=str(video_path),
        placeholder_mode=True
    )

    assert result.exists()


@pytest.mark.integration
@pytest.mark.slow
def test_studio_to_encoder_integration(tmp_path):
    """Test Studio → Encoder pipeline integration.

    Verifies that raw video from Studio can be encoded by Encoder.
    """
    pytest.skip("Requires Blender + FFmpeg - run manually")


@pytest.mark.integration
@pytest.mark.slow
def test_full_pipeline_integration(tmp_path):
    """Test complete Director → Studio → Encoder pipeline.

    This is the full end-to-end integration test.
    """
    from batch.runner import BatchRunner

    pytest.skip("Requires full setup (Blender, FFmpeg, ChromaDB) - run manually")

    runner = BatchRunner(
        audio_path="./test_audio.wav",
        song_id="test_song",
        theme="sponsor_neon",
        output_dir=str(tmp_path)
    )

    outputs = runner.run(
        platforms=["tiktok"],  # Single platform for faster testing
        with_captions=False,
        with_thumbnail=False,
        skip_studio=False
    )

    # Verify outputs
    assert "timeline" in outputs
    assert "raw_video" in outputs
    assert "video_tiktok" in outputs

    assert outputs["timeline"].exists()
    assert outputs["raw_video"].exists()
    assert outputs["video_tiktok"].exists()


def test_batch_runner_file_not_found():
    """Test BatchRunner with non-existent audio file."""
    from batch.runner import BatchRunner
    from batch.errors import StageError

    runner = BatchRunner(
        audio_path="/nonexistent/audio.wav",
        song_id="test_song"
    )

    # Should fail at Director stage with missing audio
    with pytest.raises((StageError, FileNotFoundError)):
        runner.run(skip_studio=True)
